services:
  db:
    image: mongo:6.0
    container_name: mongo_chatsimple
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin1
      - MONGO_INITDB_ROOT_PASSWORD=pass1
    restart: always
    volumes:
      - mongo_data:/data/db

  backend:
    image: peppa2k3/chatsimpledevops28be:2.0
    container_name: be_chat_2
    restart: always
    expose:
      - "3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://admin1:pass1@db:27017/chatapp?authSource=admin
      - CORS_ORIGIN=https://chat.dangngochai.io.vn
      - NODE_ENV=prod
    depends_on:
      - db
  frontend:
    image: peppa2k3/chatsimpledevops28:2.0
    container_name: fe_chat
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt
    environment:
      - PORT=80
      - REACT_APP_BACKEND_URL=https://chat.dangngochai.io.vn/api
    depends_on:
      - backend
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt
volumes:
  mongo_data:
