services:
  db:
    image: mongo:6.0
    container_name: mongo_chatsimple
    restart: always
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin1
      - MONGO_INITDB_ROOT_PASSWORD=pass1
    volumes:
      - mongo_data:/data/db
    networks: [chat-app]

  backend:
    image: peppa2k3/chatsimpledevops28be:2.0
    container_name: be_chat_2
    restart: always
    # expose:
    #   - "3000"
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - MONGODB_URI=mongodb://admin1:pass1@db:27017/chatapp?authSource=admin
      - CORS_ORIGIN=https://dangngochai.io.vn
      - NODE_ENV=prod
    depends_on:
      - db
    networks: [chat-app]

  frontend:
    image: peppa2k3/chatsimpledevops28:2.1 # image đã rebuild
    container_name: fe_chat
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PORT=80
      - REACT_APP_BACKEND_URL=https://api.dangngochai.io.vn
      - REACT_APP_SOCKET_URL=https://api.dangngochai.io.vn
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt
    depends_on:
      - backend
    networks: [chat-app]

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certs:/etc/letsencrypt

volumes:
  mongo_data:
networks:
  chat-app:
